feat:多权限请求返回值问题
react-native-oh-library/react-native-permissions pull request #2
Opened 2024-05-28 13:05 UTC by HDJKER

feat:多请求返回值类型修改

2024-05-28 13:09 UTC, HDJKER commented
feat:func "checkMultiple" reutrn {Permission[1]:GrantStatus...}

2024-05-28 13:09 UTC, HDJKER commented
feat:func "requestMultiple" reutrn {Permission[1]:GrantStatus...}

2024-05-29 02:00 UTC, Louis-C7 requested changes

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
> +    let grantStatus:PermissionStatusRecord= {};
注意格式，少空格，可合并

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
> +        grantStatus[permissions[index]]=this.checkStatus(Status);
少空格

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
> +    let resultsStatus:PermissionStatusRecord= { };
少空格，可合并
let resultsStatus: Record<string, GrantStatus> = {};

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
> +        resultsStatus[permissions[index]]=status;
少空格

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
> +
无意义修改

2024-05-29 02:00 UTC, Louis-C7 commented on harmony/permissions/src/main/ets/PermissionsModule.ts
>    async requestMultiple(permissions: Array<Permissions>): Promise<Object> {
async requestMultiple(permissions: Array<Permissions>): Promise<Record<string, GrantStatus>？

2024-05-29 02:28 UTC, Louis-C7 approved these changes

2024-05-29 02:29 UTC, merged